### PR TITLE
Doc on encodings

### PR DESCRIPTION
**Pull request by johenglisch**

### CODE REVIEW

**Review by chrzyki — APPROVED** [review]
Very great to have this, thanks!

**Comment by xrotwang** [comment]
I'd make "Normalised Forms" (or something similar) part of the respective section header, to highlight this concept - which is also important for things like orthography profiles.

**Comment by xrotwang** [comment]
Nice! Didn't know `uconv`.

**Comment by johenglisch** [comment]
@chrzyki Do you know if `uconv` is available on macos or how to get it easily?

**Comment by Bibiko** [comment]
macOS ships with `iconv` which **only** can convert encodings, but via `homebrew` -> `brew install icu4c` you get `uconv` running.

**Comment by johenglisch** [comment]
Thanks (^^)

**Pull request merged**
